[platformio]
default_envs = t5_4_7_s3

[env:t5_4_7_s3]
platform = espressif32@6.4.0
board = esp32s3box
framework = arduino
upload_protocol = esptool
upload_speed = 115200
monitor_speed = 115200
board_build.filesystem = spiffs
lib_ldf_mode = deep+
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DT5_47_PLUS_V2=1
lib_deps =
  Wire
  bblanchon/ArduinoJson@^6.21.5
  https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#esp32s3

